[program:taal-worker]
process_name=%(program_name)s_%(process_num)02d
command=php __APP_DIR__/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=__WEB_USER__
numprocs=2
redirect_stderr=true
stdout_logfile=__APP_DIR__/storage/logs/worker.log
stopwaitsecs=3600
